spring:
  application:
    name: loan-proposal-command
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mongodb:
    uri: "mongodb://localhost:27017/loan_proposal_command?replicaSet=rs0&retryWrites=false"

server:
  port: 8081
